### ISSUE TITLE
dialog back button

### ISSUE THREAD

**Issue by Mikeichhalt** [benlau/quickandroid#14]
Hi,

The app closes earlier, when you open an dialog and use the back button from android device twice.
I found this issue in your example project:
quickandroid/examples/quickandroidexample/dialog/DialogDemo.qml

**Comment by benlau** [comment]
Thanks for reporting. I could confirm this bug. Will fix it.

**Comment by benlau** [comment]
Hi,

Just released v0.1.6 with fix for this issue.

**Comment by Mikeichhalt** [comment]
thx, now it works :)
