### ISSUE TITLE
can not build the example pro in ubuntu 15.10

### ISSUE THREAD

**Issue by wubohan2011** [benlau/quickandroid#18]
Hello @benlau! Thank you for such a nice project.  

I just downloaded the newest version of quickandroid and compiled its example project in Ubuntu 15.10. and QT 5.4.2. I got the desktop version run smoothly. However, with ant and QT5.4.2, the apk package was created but can not install to an android 4.4 mobile. with gradle I got an error about invalid version: Android 4.4. 

My android SDK is android api 19, NDK is ndk-r10. Is there something that I am missing?

**Comment by benlau** [comment]
Can you build Qt example program and run on Android?

**Comment by wubohan2011** [comment]
I can build the example project in current version of quickandroid but I can't run it in my Android 4.4 mobile. However, I found cyberbobs had an older version of quickandroid and I can build & run it in this mobile:
https://github.com/cyberbobs/quickandroid

**Comment by benlau** [comment]
Could you post the console log?

**Comment by wubohan2011** [comment]
Thinks for the reply. I solved this problem already. It seems the problem is caused by a mistake in my NDK setting.  I do like your code, best wish.

**Comment by benlau** [comment]
I am migrating to use gradle to build the project and I got similar problem. It complains: "Invalid Revision: android-4.4.2"

I fix this problem by removing "android-4.4.2" folder within the build-tools folder in Android sdk. Then clean the build , restart Qt Creator.
