### ISSUE TITLE
Drawable issue

### ISSUE THREAD

**Issue by ducmaxime** [benlau/quickandroid#20]
Hello,

I try to use FloatingActionButton but I have this error with drawable:

 QML Image: Invalid image provider: image://drawable/ic_done_black_24dp?tintColor=%23deffffff

Any Idea ?

**Comment by benlau** [comment]
Are you copy the code from example program directly?
e.g
```
FloatingActionButton {
                    backgroundColor: "blue"
                    iconSource: A.drawable("ic_done_black_24dp",Constants.white87);
                    depth: modelData
                    anchors.verticalCenter: parent.verticalCenter
                    size: Constants.small
                }
```

It can't load the ic_done_black_24dp becoz the image provider of "drawable" is not installed. Please refer to this piece of code to how to install the provider:

[quickandroid/main.cpp at master · benlau/quickandroid](https://github.com/benlau/quickandroid/blob/master/examples/quickandroidexample/main.cpp#L44)

**Comment by ducmaxime** [comment]
Yes its working fine.

Thank you
