### ISSUE TITLE
QPM installation error

### ISSUE THREAD

**Issue by artemiss** [benlau/quickandroid#23]
QPM: 2016/07/11 18:19:03 ERROR: GetFileAttributesEx %path%\vendor\benlau-quickandroid-74762b4\tools\ninepatchconverter\qpm.json: The system cannot find the file specified.

**Comment by benlau** [comment]
hi @artemiss ,

It seem to be a problem of qpm. I think it is better to seek help from https://github.com/Cutehacks/qpm
