### ISSUE TITLE
Native TextInput widget

### ISSUE THREAD

**Issue by paulondc** [benlau/quickandroid#27]
Hi,

I wonder if you are planning to add support for the native text input widget that's available in android as a wrapped control for QML? I'm asking it because currently Qt's TextInput doesn't provide a good usability that works well in touchscreen for dealing with selection markers and text cursor position.

Cheers

**Comment by benlau** [comment]
I am interested with this feature. But I have no idea how to make it yet.

**Comment by paulondc** [comment]
You could base your implementation for android based on the library bellow:
https://github.com/2gis/qtandroidextensions (Take a look at QtOffscreenViews/QAndroidOffscreenView.h)

Also, there's another one for IOS 
https://github.com/bdentino/Qtino.NativeTextInput

I don't think it needs to provide all sorts of customisation aka Qt's TextInput provides, however it would be very handy to have a single interface for the native TextInput that would be supported by both Android and IOS, so following a implementation design like react-native modules. 

An issue that I see very often in QML modules that are distributed through qpm is the fact that they bring too much functionally rather than focusing to be as minimal as possible, so not taking advantage of having a dependence system that takes care of installing dependencies automatically and at same discouraging users to contribute/use them because the large amount of complexity associated with them. Which brings to my next suggestion:

What about to create a new github repository aka "qml-native-components" that would contain only wrappers which can be both used by Android and IOS, like the ImagePicker and TextInput for now ?

Cheers

**Comment by benlau** [comment]
Thx.

I have taken a quick glance on qtandroidextensions but I don't quite understand how it pass touch event from QT to Android component. 

By the way, as the qtandroidextensions project has already implemented the feature. Why don't just use their library?

In fact, I am also considering to break down this project. Probably it will have a library for SystemDispatcher, and image picker as another module. But I don't have solid plan yet.  At least I won't go if Text Input is too difficult to implement.

**Comment by paulondc** [comment]
I'm favouring to use small libraries that are available through qpm which don't have too much complexity involved on that. I thought that QuickAndroid would be a nice place for it because you also have the QuickIos, therefore since Qt's TextInput is an issue in any mobile platform it would be very convenient to have it in libraries that provide the same api.

About the ImagePicker, could you double check if that is working for you ? in my tests it shows the chooser interface, however after hitting Ok, it does not set the image path (fileUrl), it seems like somehow it's failing to resolve the image path (tested on android 5.0).

In order to use the ImagePicker is there any special permission that I need to add to my "AndroidManifest.xml" beside of "android.permission.READ_EXTERNAL_STORAGE" and  "android.permission.WRITE_EXTERNAL_STORAGE" ?

Cheers

**Comment by benlau** [comment]
About the image picker, it is working. You may try the pre-build APK at:
https://drone.io/github.com/benlau/quickandroid/files

I guess it is because your activity class do not forward the onActivityResult to Image Picker. You may take a look at the QuickAndroidActivitiy.java:

https://github.com/benlau/quickandroid/blob/master/java/quickandroid/QuickAndroidActivity.java#L14

```
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        SystemDispatcher.onActivityResult(requestCode,resultCode,data);
    }
```

**Comment by paulondc** [comment]
I've decided to implement my own picker. Thanks for all.

Cheers
