### ISSUE TITLE
Push notification service

### ISSUE THREAD

**Issue by deadwolfst** [benlau/quickandroid#34]
Is it possible to create a push notifications with quickandroid? For example, websocket + appropriate server side. Is included SystemDispatcher supports this functionality or how i should rewrite it for this?

**Comment by benlau** [comment]
SystemDispatcher is an utility communicate between C++ and Java code that avoid JNI code. So I should be possible.

e.g Implement notification service in Java and web socket in C++ (http://doc.qt.io/qt-5/qtwebsockets-index.html)
